start to only loop for chunks

diff --git a/tests/md/rc b/tests/md/rc
--- a/tests/md/rc
+++ b/tests/md/rc
@@ -96,136 +96,143 @@ _md_atomics_test() {
 	echo "finally expected_atomic_write_supported="$expected_atomic_write_supported
 
 	for raid_level in 0 1 10; do
-		echo "raid_level="$raid_level
-		echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-			--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
-			/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
-
-		md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
-		md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"
-
-		md_sysfs_logical_block_size=$(< "${md_dev_sysfs}"/queue/logical_block_size)
-#		echo "md_sysfs_logical_block_size="$md_sysfs_logical_block_size
-		md_sysfs_max_hw_sectors_kb=$(< "${md_dev_sysfs}"/queue/max_hw_sectors_kb)
-#		echo "md_sysfs_max_hw_sectors_kb="$md_sysfs_max_hw_sectors_kb
-		md_max_hw=$(( "$md_sysfs_max_hw_sectors_kb" * 1024 ))
-#		echo "md_max_hw="$md_max_hw
-		md_sysfs_atomic_max=$(< "${md_dev_sysfs}"/queue/atomic_write_max_bytes)
-#		echo "md_sysfs_atomic_max="$md_sysfs_atomic_max
-		md_sysfs_atomic_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
-#		echo "md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max
-		md_sysfs_atomic_unit_min=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_min_bytes)
-#		echo "md_sysfs_atomic_unit_min="$md_sysfs_atomic_unit_min
-		md_sysfs_atomic_boundary=$(< "${md_dev_sysfs}"/queue/atomic_write_boundary_bytes)
-		echo "md_sysfs_atomic_boundary="$md_sysfs_atomic_boundary
-#		md_atomic_unit_max=$(( "$scsi_debug_atomic_wr_max_length" * "$md_sysfs_logical_block_size" ))
-#		echo "md_atomic_unit_max="$md_atomic_unit_max
-#		md_atomic_unit_min=$(( "$scsi_debug_atomic_wr_gran" * "$md_sysfs_logical_block_size" ))
-#		echo "md_atomic_unit_min="$md_atomic_unit_min
-
-		test_desc="TEST 1 RAID $raid_level - Verify md sysfs atomic attributes matches"
-		if [ "$md_sysfs_atomic_unit_max" = "$expected_atomic_write_unit_max" ] &&
-			[ "$md_sysfs_atomic_unit_min" = "$expected_atomic_write_unit_min" ]
+		# We loop for different chunk sizes, even though it is not relevant to RAID1
+		chunk_gran=$(( "$expected_atomic_write_unit_max" / 4))
+		if [ "$chunk_gran" -lt "$expected_atomic_write_unit_min" ]
 		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_write_unit_max and " \
-				"$md_sysfs_atomic_unit_min - $expected_atomic_write_unit_min "
+			chunk_gran=$expected_atomic_write_unit_min
 		fi
+		local chunk_multiple=1
+		for step in `seq 1 6`
+		do
+			echo "chunky1 chunk_gran="$chunk_gran" raid_level="$raid_level" step="$step
+			local expected_chunk_atomic_unit_min
+			local expected_chunk_atomic_unit_max
+			local expected_chunk_atomic_max
+			local expected_chunk_atomic_boundary
 
-		test_desc="TEST 2 RAID $raid_level - Verify sysfs atomic attributes"
-		if [ "$md_max_hw" -ge "$md_sysfs_atomic_max" ] &&
-			[ "$md_sysfs_atomic_max" -ge "$md_sysfs_atomic_unit_max" ] &&
-			[ "$md_sysfs_atomic_unit_max" -ge "$md_sysfs_atomic_unit_min" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $md_max_hw - $md_sysfs_max_hw_sectors_kb -" \
-				"$md_sysfs_atomic_max - $md_sysfs_atomic_unit_max -" \
-				"$md_sysfs_atomic_unit_min"
-		fi
+			if [ "$raid_level" = 0 ]
+			then
+				chunk_multiple=$step
+			else
+				chunk_multiple=$(( 2 * "$chunk_multiple"))
+			fi
+			md_chunk_size=$(( "$chunk_gran" * "$chunk_multiple"))
+			echo "chunky2 md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple
+			md_chunk_size_kb=$(( "$md_chunk_size" / 1024))
 
-		test_desc="TEST 3 RAID $raid_level - Verify md sysfs_atomic_max_bytes is less than or equal "
-		test_desc+="sysfs_atomic_max_bytes"
-		if [ "$md_sysfs_atomic_max" -le "$expected_atomic_write_max" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $md_sysfs_atomic_max - $expected_atomic_write_max"
-		fi
+			if [ "$raid_level" = 0 ] || [ "$raid_level" = 10 ]
+			then
+				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
+					 --chunk="${md_chunk_size_kb}"K \
+					--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
+					/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
+			else
+				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
+					--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
+					/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
+			fi
 
-		test_desc="TEST 4 RAID $raid_level - check sysfs atomic_write_unit_max_bytes <=  expected_atomic_write_unit_max"
-		if [ "$md_sysfs_atomic_unit_max" -le "$expected_atomic_write_unit_max" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_write_unit_max"
-		fi
+			md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
+			md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"
 
-		test_desc="TEST 5 RAID $raid_level - check sysfs atomic_write_unit_min_bytes = expected atomic_write_unit_min_bytes"
-		if [ "$md_sysfs_atomic_unit_min" = "$expected_atomic_write_unit_min" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_min - $expected_atomic_write_unit_min"
-		fi
+			md_sysfs_logical_block_size=$(< "${md_dev_sysfs}"/queue/logical_block_size)
+	#		echo "md_sysfs_logical_block_size="$md_sysfs_logical_block_size
+			md_sysfs_max_hw_sectors_kb=$(< "${md_dev_sysfs}"/queue/max_hw_sectors_kb)
+	#		echo "md_sysfs_max_hw_sectors_kb="$md_sysfs_max_hw_sectors_kb
+			md_max_hw=$(( "$md_sysfs_max_hw_sectors_kb" * 1024 ))
+	#		echo "md_max_hw="$md_max_hw
+			md_sysfs_atomic_max=$(< "${md_dev_sysfs}"/queue/atomic_write_max_bytes)
+	#		echo "md_sysfs_atomic_max="$md_sysfs_atomic_max
+			md_sysfs_atomic_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
+	#		echo "md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max
+			md_sysfs_atomic_unit_min=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_min_bytes)
+	#		echo "md_sysfs_atomic_unit_min="$md_sysfs_atomic_unit_min
+			md_sysfs_atomic_boundary=$(< "${md_dev_sysfs}"/queue/atomic_write_boundary_bytes)
+			echo "md_sysfs_atomic_boundary="$md_sysfs_atomic_boundary
+	#		md_atomic_unit_max=$(( "$scsi_debug_atomic_wr_max_length" * "$md_sysfs_logical_block_size" ))
+	#		echo "md_atomic_unit_max="$md_atomic_unit_max
+	#		md_atomic_unit_min=$(( "$scsi_debug_atomic_wr_gran" * "$md_sysfs_logical_block_size" ))
+	#		echo "md_atomic_unit_min="$md_atomic_unit_min
 
-		test_desc="TEST 6 RAID $raid_level - check statx stx_atomic_write_unit_min"
-		statx_atomic_min=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_min")
-		if [ "$statx_atomic_min" = "$md_sysfs_atomic_unit_min" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $statx_atomic_min - $md_sysfs_atomic_unit_min"
-		fi
+			test_desc="TEST 1 RAID $raid_level - Verify md sysfs atomic attributes matches"
+			if [ "$md_sysfs_atomic_unit_max" = "$expected_atomic_write_unit_max" ] &&
+				[ "$md_sysfs_atomic_unit_min" = "$expected_atomic_write_unit_min" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_write_unit_max and " \
+					"$md_sysfs_atomic_unit_min - $expected_atomic_write_unit_min "
+			fi
 
-		test_desc="TEST 7 RAID $raid_level - check statx stx_atomic_write_unit_max"
-		statx_atomic_max=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_max")
-		if [ "$statx_atomic_max" = "$md_sysfs_atomic_unit_max" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $statx_atomic_max - $md_sysfs_atomic_unit_max"
-		fi
+			test_desc="TEST 2 RAID $raid_level - Verify sysfs atomic attributes"
+			if [ "$md_max_hw" -ge "$md_sysfs_atomic_max" ] &&
+				[ "$md_sysfs_atomic_max" -ge "$md_sysfs_atomic_unit_max" ] &&
+				[ "$md_sysfs_atomic_unit_max" -ge "$md_sysfs_atomic_unit_min" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $md_max_hw - $md_sysfs_max_hw_sectors_kb -" \
+					"$md_sysfs_atomic_max - $md_sysfs_atomic_unit_max -" \
+					"$md_sysfs_atomic_unit_min"
+			fi
 
-		test_desc="TEST 8 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes with "
-		test_desc+="RWF_ATOMIC flag - pwritev2 should be succesful"
-		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_max")
-		if [ "$bytes_written" = "$md_sysfs_atomic_unit_max" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $bytes_written - $md_sysfs_atomic_unit_max"
-		fi
+			test_desc="TEST 3 RAID $raid_level - Verify md sysfs_atomic_max_bytes is less than or equal "
+			test_desc+="sysfs_atomic_max_bytes"
+			if [ "$md_sysfs_atomic_max" -le "$expected_atomic_write_max" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $md_sysfs_atomic_max - $expected_atomic_write_max"
+			fi
 
-		test_desc="TEST 9 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes + 512 "
-		test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should not be succesful"
-		bytes_to_write=$(( "${md_sysfs_atomic_unit_max}" + 512 ))
-		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
-		if [ "$bytes_written" = "" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $bytes_written - $bytes_to_write"
-		fi
+			test_desc="TEST 4 RAID $raid_level - check sysfs atomic_write_unit_max_bytes <=  expected_atomic_write_unit_max"
+			if [ "$md_sysfs_atomic_unit_max" -le "$expected_atomic_write_unit_max" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_write_unit_max"
+			fi
 
-		test_desc="TEST 10 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_min_bytes "
-		test_desc+="with RWF_ATOMIC flag - pwritev2 should be succesful"
-		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_min")
-		if [ "$bytes_written" = "$md_sysfs_atomic_unit_min" ]
-		then
-			echo "$test_desc - pass"
-		else
-			echo "$test_desc - fail $bytes_written - $md_atomic_unit_min"
-		fi
+			test_desc="TEST 5 RAID $raid_level - check sysfs atomic_write_unit_min_bytes = expected atomic_write_unit_min_bytes"
+			if [ "$md_sysfs_atomic_unit_min" = "$expected_atomic_write_unit_min" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $md_sysfs_atomic_unit_min - $expected_atomic_write_unit_min"
+			fi
 
-		bytes_to_write=$(( "${md_sysfs_atomic_unit_min}" - "${md_sysfs_logical_block_size}" ))
-		test_desc="TEST 11 RAID $raid_level - perform a pwritev2 with a size of sysfs_atomic_unit_min_bytes - 512 "
-		test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should fail"
-		if [ "$bytes_to_write" = 0 ]
-		then
-			echo "$test_desc - pass"
-		else
+			test_desc="TEST 6 RAID $raid_level - check statx stx_atomic_write_unit_min"
+			statx_atomic_min=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_min")
+			if [ "$statx_atomic_min" = "$md_sysfs_atomic_unit_min" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $statx_atomic_min - $md_sysfs_atomic_unit_min"
+			fi
+
+			test_desc="TEST 7 RAID $raid_level - check statx stx_atomic_write_unit_max"
+			statx_atomic_max=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_max")
+			if [ "$statx_atomic_max" = "$md_sysfs_atomic_unit_max" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $statx_atomic_max - $md_sysfs_atomic_unit_max"
+			fi
+
+			test_desc="TEST 8 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes with "
+			test_desc+="RWF_ATOMIC flag - pwritev2 should be succesful"
+			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_max")
+			if [ "$bytes_written" = "$md_sysfs_atomic_unit_max" ]
+			then
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $bytes_written - $md_sysfs_atomic_unit_max"
+			fi
+
+			test_desc="TEST 9 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes + 512 "
+			test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should not be succesful"
+			bytes_to_write=$(( "${md_sysfs_atomic_unit_max}" + 512 ))
 			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
 			if [ "$bytes_written" = "" ]
 			then
@@ -233,64 +240,37 @@ _md_atomics_test() {
 			else
 				echo "$test_desc - fail $bytes_written - $bytes_to_write"
 			fi
-		fi
-		mdadm --stop /dev/md/blktests_md  2> /dev/null 1>&2
-		mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
-		mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
-		mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
-		mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
 
-		if [ "$raid_level" = 0 ] || [ "$raid_level" = 10 ]
-		then
-			chunk_gran=$(( "$expected_atomic_write_unit_max" / 4))
-			if [ "$chunk_gran" -lt "$expected_atomic_write_unit_min" ]
+			test_desc="TEST 10 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_min_bytes "
+			test_desc+="with RWF_ATOMIC flag - pwritev2 should be succesful"
+			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_min")
+			if [ "$bytes_written" = "$md_sysfs_atomic_unit_min" ]
 			then
-				chunk_gran=$expected_atomic_write_unit_min
+				echo "$test_desc - pass"
+			else
+				echo "$test_desc - fail $bytes_written - $md_atomic_unit_min"
 			fi
-			local chunk_multiple=1
-			for step in `seq 1 6`
-			do
-				echo "chunky1 chunk_gran="$chunk_gran" raid_level="$raid_level" step="$step
-				local expected_chunk_atomic_unit_min
-				local expected_chunk_atomic_unit_max
-				local expected_chunk_atomic_max
-				local expected_chunk_atomic_boundary
-				
 
-				if [ "$raid_level" = 0 ]
-				then
-					chunk_multiple=$step
-				else
-					chunk_multiple=$(( 2 * "$chunk_multiple"))
-				fi
-				md_chunk_size=$(( "$chunk_gran" * "$chunk_multiple"))
-				echo "chunky2 md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple
-				md_chunk_size_kb=$(( "$md_chunk_size" / 1024))
-
-				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-						--raid-devices=4 --chunk="${md_chunk_size_kb}"K --force \
-						/dev/"${dev0}" /dev/"${dev1}" \
-						/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
-				
-				md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
-				md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"
-				md_sysfs_atomic_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
-				test_desc="TEST 12 RAID $raid_level - Verify chunk size "
-				echo "chunky3x md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple" md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max
-				if [ "$md_chunk_size" -ge "$md_sysfs_atomic_unit_max" ] && \
-					(( md_chunk_size % md_sysfs_atomic_unit_max == 0 ))
+			bytes_to_write=$(( "${md_sysfs_atomic_unit_min}" - "${md_sysfs_logical_block_size}" ))
+			test_desc="TEST 11 RAID $raid_level - perform a pwritev2 with a size of sysfs_atomic_unit_min_bytes - 512 "
+			test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should fail"
+			if [ "$bytes_to_write" = 0 ]
+			then
+				echo "$test_desc - pass"
+			else
+				bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
+				if [ "$bytes_written" = "" ]
 				then
 					echo "$test_desc - pass"
 				else
-					echo $test_desc" - fail md_chunk_size="$md_chunk_size" md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max" chunk_multiple="$chunk_multiple
+					echo "$test_desc - fail $bytes_written - $bytes_to_write"
 				fi
-
-				mdadm --quiet --stop /dev/md/blktests_md
-				mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
-				mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
-				mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
-				mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
-			done
-		fi
+			fi
+			mdadm --stop /dev/md/blktests_md  2> /dev/null 1>&2
+			mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
+			mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
+			mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
+			mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
+		done
 	done
 }
