stop using bytes

diff --git a/tests/md/rc b/tests/md/rc
--- a/tests/md/rc
+++ b/tests/md/rc
@@ -15,27 +15,26 @@ group_requires() {
 declare -A MD_DEVICES
 
 _md_atomics_test() {
-	local md_atomic_max_bytes
-	local md_atomic_min_bytes
+	local md_atomic_unit_max
+	local md_atomic_unit_min
 	local md_sysfs_max_hw_sectors_kb
-	local md_max_hw_bytes
+	local md_max_hw
 	local md_chunk_size
-	local md_chunk_size_bytes
+	local md_chunk_size
 	local md_sysfs_logical_block_size
-	local md_sysfs_atomic_max_bytes
-	local md_sysfs_atomic_unit_max_bytes
-	local md_sysfs_atomic_unit_min_bytes
+	local md_sysfs_atomic_max
+	local md_sysfs_atomic_unit_max
+	local md_sysfs_atomic_unit_min
 	local bytes_to_write
 	local bytes_written
 	local test_desc
 	local md_dev
 	local md_dev_sysfs
-	local expected_atomic_unit_min_bytes
-	local expected_atomic_unit_max_bytes
-	local expected_atomic_max_bytes
-	local expected_atomic_boundary_bytes
-	local atomic_supported=1
-	local md_chunk_size
+	local expected_atomic_unit_min
+	local expected_atomic_unit_max
+	local expected_atomic_max
+	local expected_atomic_boundary
+	local expected_atomic_supported=1
 
 	dev0=$1
 	dev1=$2
@@ -45,71 +44,62 @@ _md_atomics_test() {
 	unset MD_DEVICES
 	MD_DEVICES=($dev0 $dev1 $dev2 $dev3);
 
-	expected_atomic_unit_min_bytes=$(< /sys/block/"$dev0"/queue/atomic_write_unit_min_bytes);
-	expected_atomic_unit_max_bytes=$(< /sys/block/"$dev0"/queue/atomic_write_unit_max_bytes);
-	expected_atomic_max_bytes=$(< /sys/block/"$dev0"/queue/atomic_write_max_bytes);
-	expected_atomic_boundary_bytes=$(< /sys/block/"$dev0"/queue/atomic_write_boundary_bytes);
+	expected_atomic_unit_min=$(< /sys/block/"$dev0"/queue/atomic_write_unit_min_bytes);
+	expected_atomic_unit_max=$(< /sys/block/"$dev0"/queue/atomic_write_unit_max_bytes);
+	expected_atomic_max=$(< /sys/block/"$dev0"/queue/atomic_write_max_bytes);
+	expected_atomic_boundary=$(< /sys/block/"$dev0"/queue/atomic_write_boundary_bytes);
 
-#	echo "before expected_atomic_unit_min_bytes="$expected_atomic_unit_min_bytes
-#	echo "before expected_atomic_unit_max_bytes="$expected_atomic_unit_max_bytes
-#	echo "before expected_atomic_max_bytes="$expected_atomic_max_bytes
-#	echo "before expected_atomic_boundary_bytes="$expected_atomic_boundary_bytes
-#	echo "before atomic_supported="$atomic_supported
+#	echo "before expected_atomic_unit_min="$expected_atomic_unit_min
+#	echo "before expected_atomic_unit_max="$expected_atomic_unit_max
+#	echo "before expected_atomic_max="$expected_atomic_max
+#	echo "before expected_atomic_boundary="$expected_atomic_boundary
+#	echo "before expected_atomic_supported="$expected_atomic_supported
 	for i in "${MD_DEVICES[@]}"; do
 		echo "llowwpiu MD_DEVICES="$i" unit min="$(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes)
 		echo "llowwpiu MD_DEVICES="$i" unit max="$(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes)
 		echo "llowwpiu MD_DEVICES="$i" max="$(< /sys/block/"$i"/queue/atomic_write_max_bytes)
 		echo "llowwpiu MD_DEVICES="$i" boundary="$(< /sys/block/"$i"/queue/atomic_write_boundary_bytes)
-		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes) -gt expected_atomic_unit_min_bytes ]]; then
-			expected_atomic_unit_min_bytes=$(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes)
+		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes) -gt expected_atomic_unit_min ]]; then
+			expected_atomic_unit_min=$(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes)
 		fi
-		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes) -lt expected_atomic_unit_max_bytes ]]; then
-			expected_atomic_unit_max_bytes=$(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes)
+		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes) -lt expected_atomic_unit_max ]]; then
+			expected_atomic_unit_max=$(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes)
 		fi
-		if [[ $(< /sys/block/"$i"/queue/atomic_write_max_bytes) -lt expected_atomic_max_bytes ]]; then
-			expected_atomic_max_bytes=$(< /sys/block/"$i"/queue/atomic_write_max_bytes)
+		if [[ $(< /sys/block/"$i"/queue/atomic_write_max_bytes) -lt expected_atomic_max ]]; then
+			expected_atomic_max=$(< /sys/block/"$i"/queue/atomic_write_max_bytes)
 		fi
 		# The kernel only supports same boundary size for all devices in the array
-		if [[ $(< /sys/block/"$i"/queue/atomic_write_boundary_bytes) -ne expected_atomic_boundary_bytes ]]; then
-			let atomic_supported=0;
+		if [[ $(< /sys/block/"$i"/queue/atomic_write_boundary_bytes) -ne expected_atomic_boundary ]]; then
+			let expected_atomic_supported=0;
 		fi
 	done
 
-#	echo "after expected_atomic_unit_min_bytes="$expected_atomic_unit_min_bytes
-#	echo "after expected_atomic_unit_max_bytes="$expected_atomic_unit_max_bytes
-#	echo "after expected_atomic_max_bytes="$expected_atomic_max_bytes
-#	echo "after expected_atomic_boundary_bytes="$expected_atomic_boundary_bytes
-#	echo "after atomic_supported="$atomic_supported
+#	echo "after expected_atomic_unit_min="$expected_atomic_unit_min
+#	echo "after expected_atomic_unit_max="$expected_atomic_unit_max
+#	echo "after expected_atomic_max="$expected_atomic_max
+#	echo "after expected_atomic_boundary="$expected_atomic_boundary
+#	echo "after expected_atomic_supported="$expected_atomic_supported
 
 	# We cannot support atomic writes for the array of devices supported
 	# However we can still test that the stacked device does not support
 	# atomic writes (which it shouldn't).
-	if [[ atomic_supported -eq 0 ]]; then
-		let expected_atomic_unit_min_bytes=0;
-		let expected_atomic_unit_max_bytes=0;
-		let expected_atomic_max_bytes=0;
-		let expected_atomic_boundary_bytes=0;
+	if [[ expected_atomic_supported -eq 0 ]]; then
+		let expected_atomic_unit_min=0;
+		let expected_atomic_unit_max=0;
+		let expected_atomic_max=0;
+		let expected_atomic_boundary=0;
 	fi
-	echo "finally expected_atomic_unit_min_bytes="$expected_atomic_unit_min_bytes
-	echo "finally expected_atomic_unit_max_bytes="$expected_atomic_unit_max_bytes
-	echo "finally expected_atomic_max_bytes="$expected_atomic_max_bytes
-	echo "finally expected_atomic_boundary_bytes="$expected_atomic_boundary_bytes
-	echo "finally atomic_supported="$atomic_supported
+	echo "finally expected_atomic_unit_min="$expected_atomic_unit_min
+	echo "finally expected_atomic_unit_max="$expected_atomic_unit_max
+	echo "finally expected_atomic_max="$expected_atomic_max
+	echo "finally expected_atomic_boundary="$expected_atomic_boundary
+	echo "finally expected_atomic_supported="$expected_atomic_supported
 
 	for raid_level in 0 1 10; do
 		echo "raid_level="$raid_level
-		if [ "$raid_level" = 10 ]
-		then
-			echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-				--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
-				/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
-		else
-			echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-				--raid-devices=2 --force \
-				/dev/"${dev0}" /dev/"${dev1}" 2> /dev/null 1>&2
-		fi
-
-	
+		echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
+			--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
+			/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
 
 		md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
 		md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"
@@ -118,99 +108,99 @@ _md_atomics_test() {
 #		echo "md_sysfs_logical_block_size="$md_sysfs_logical_block_size
 		md_sysfs_max_hw_sectors_kb=$(< "${md_dev_sysfs}"/queue/max_hw_sectors_kb)
 #		echo "md_sysfs_max_hw_sectors_kb="$md_sysfs_max_hw_sectors_kb
-		md_max_hw_bytes=$(( "$md_sysfs_max_hw_sectors_kb" * 1024 ))
-#		echo "md_max_hw_bytes="$md_max_hw_bytes
-		md_sysfs_atomic_max_bytes=$(< "${md_dev_sysfs}"/queue/atomic_write_max_bytes)
-#		echo "md_sysfs_atomic_max_bytes="$md_sysfs_atomic_max_bytes
-		md_sysfs_atomic_unit_max_bytes=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
-#		echo "md_sysfs_atomic_unit_max_bytes="$md_sysfs_atomic_unit_max_bytes
-		md_sysfs_atomic_unit_min_bytes=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_min_bytes)
-#		echo "md_sysfs_atomic_unit_min_bytes="$md_sysfs_atomic_unit_min_bytes
-		md_sysfs_atomic_boundary_bytes=$(< "${md_dev_sysfs}"/queue/atomic_write_boundary_bytes)
-		echo "md_sysfs_atomic_boundary_bytes="$md_sysfs_atomic_boundary_bytes
-#		md_atomic_max_bytes=$(( "$scsi_debug_atomic_wr_max_length" * "$md_sysfs_logical_block_size" ))
-#		echo "md_atomic_max_bytes="$md_atomic_max_bytes
-#		md_atomic_min_bytes=$(( "$scsi_debug_atomic_wr_gran" * "$md_sysfs_logical_block_size" ))
-#		echo "md_atomic_min_bytes="$md_atomic_min_bytes
+		md_max_hw=$(( "$md_sysfs_max_hw_sectors_kb" * 1024 ))
+#		echo "md_max_hw="$md_max_hw
+		md_sysfs_atomic_max=$(< "${md_dev_sysfs}"/queue/atomic_write_max_bytes)
+#		echo "md_sysfs_atomic_max="$md_sysfs_atomic_max
+		md_sysfs_atomic_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
+#		echo "md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max
+		md_sysfs_atomic_unit_min=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_min_bytes)
+#		echo "md_sysfs_atomic_unit_min="$md_sysfs_atomic_unit_min
+		md_sysfs_atomic_boundary=$(< "${md_dev_sysfs}"/queue/atomic_write_boundary_bytes)
+		echo "md_sysfs_atomic_boundary="$md_sysfs_atomic_boundary
+#		md_atomic_unit_max=$(( "$scsi_debug_atomic_wr_max_length" * "$md_sysfs_logical_block_size" ))
+#		echo "md_atomic_unit_max="$md_atomic_unit_max
+#		md_atomic_unit_min=$(( "$scsi_debug_atomic_wr_gran" * "$md_sysfs_logical_block_size" ))
+#		echo "md_atomic_unit_min="$md_atomic_unit_min
 
 		test_desc="TEST 1 RAID $raid_level - Verify md sysfs atomic attributes matches"
-		if [ "$md_sysfs_atomic_unit_max_bytes" = "$expected_atomic_unit_max_bytes" ] &&
-			[ "$md_sysfs_atomic_unit_min_bytes" = "$expected_atomic_unit_min_bytes" ]
+		if [ "$md_sysfs_atomic_unit_max" = "$expected_atomic_unit_max" ] &&
+			[ "$md_sysfs_atomic_unit_min" = "$expected_atomic_unit_min" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_max_bytes - $expected_atomic_unit_max_bytes and " \
-				"$md_sysfs_atomic_unit_min_bytes - $expected_atomic_unit_min_bytes "
+			echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_unit_max and " \
+				"$md_sysfs_atomic_unit_min - $expected_atomic_unit_min "
 		fi
 
 		test_desc="TEST 2 RAID $raid_level - Verify sysfs atomic attributes"
-		if [ "$md_max_hw_bytes" -ge "$md_sysfs_atomic_max_bytes" ] &&
-			[ "$md_sysfs_atomic_max_bytes" -ge "$md_sysfs_atomic_unit_max_bytes" ] &&
-			[ "$md_sysfs_atomic_unit_max_bytes" -ge "$md_sysfs_atomic_unit_min_bytes" ]
+		if [ "$md_max_hw" -ge "$md_sysfs_atomic_max" ] &&
+			[ "$md_sysfs_atomic_max" -ge "$md_sysfs_atomic_unit_max" ] &&
+			[ "$md_sysfs_atomic_unit_max" -ge "$md_sysfs_atomic_unit_min" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $md_max_hw_bytes - $md_sysfs_max_hw_sectors_kb -" \
-				"$md_sysfs_atomic_max_bytes - $md_sysfs_atomic_unit_max_bytes -" \
-				"$md_sysfs_atomic_unit_min_bytes"
+			echo "$test_desc - fail $md_max_hw - $md_sysfs_max_hw_sectors_kb -" \
+				"$md_sysfs_atomic_max - $md_sysfs_atomic_unit_max -" \
+				"$md_sysfs_atomic_unit_min"
 		fi
 
 		test_desc="TEST 3 RAID $raid_level - Verify md sysfs_atomic_max_bytes is less than or equal "
 		test_desc+="sysfs_atomic_max_bytes"
-		if [ "$md_sysfs_atomic_max_bytes" -le "$expected_atomic_max_bytes" ]
+		if [ "$md_sysfs_atomic_max" -le "$expected_atomic_max" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $md_sysfs_atomic_max_bytes - $expected_atomic_max_bytes"
+			echo "$test_desc - fail $md_sysfs_atomic_max - $expected_atomic_max"
 		fi
 
 		test_desc="TEST 4 RAID $raid_level - check sysfs atomic_write_unit_max_bytes <= debug atomic_wr_max_length"
-		if [ "$md_sysfs_atomic_unit_max_bytes" -le "$expected_atomic_unit_max_bytes" ]
+		if [ "$md_sysfs_atomic_unit_max" -le "$expected_atomic_unit_max" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_max_bytes - $expected_atomic_unit_max_bytes"
+			echo "$test_desc - fail $md_sysfs_atomic_unit_max - $expected_atomic_unit_max"
 		fi
 
 		test_desc="TEST 5 RAID $raid_level - check sysfs atomic_write_unit_min_bytes = expected atomic_write_unit_min_bytes"
-		if [ "$md_sysfs_atomic_unit_min_bytes" = "$expected_atomic_unit_min_bytes" ]
+		if [ "$md_sysfs_atomic_unit_min" = "$expected_atomic_unit_min" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $md_sysfs_atomic_unit_min_bytes - $expected_atomic_unit_min_bytes"
+			echo "$test_desc - fail $md_sysfs_atomic_unit_min - $expected_atomic_unit_min"
 		fi
 
 		test_desc="TEST 6 RAID $raid_level - check statx stx_atomic_write_unit_min"
 		statx_atomic_min=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_min")
-		if [ "$statx_atomic_min" = "$md_sysfs_atomic_unit_min_bytes" ]
+		if [ "$statx_atomic_min" = "$md_sysfs_atomic_unit_min" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $statx_atomic_min - $md_sysfs_atomic_unit_min_bytes"
+			echo "$test_desc - fail $statx_atomic_min - $md_sysfs_atomic_unit_min"
 		fi
 
 		test_desc="TEST 7 RAID $raid_level - check statx stx_atomic_write_unit_max"
 		statx_atomic_max=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_max")
-		if [ "$statx_atomic_max" = "$md_sysfs_atomic_unit_max_bytes" ]
+		if [ "$statx_atomic_max" = "$md_sysfs_atomic_unit_max" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $statx_atomic_max - $md_sysfs_atomic_unit_max_bytes"
+			echo "$test_desc - fail $statx_atomic_max - $md_sysfs_atomic_unit_max"
 		fi
 
 		test_desc="TEST 8 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes with "
 		test_desc+="RWF_ATOMIC flag - pwritev2 should be succesful"
-		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_max_bytes")
-		if [ "$bytes_written" = "$md_sysfs_atomic_unit_max_bytes" ]
+		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_max")
+		if [ "$bytes_written" = "$md_sysfs_atomic_unit_max" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $bytes_written - $md_sysfs_atomic_unit_max_bytes"
+			echo "$test_desc - fail $bytes_written - $md_sysfs_atomic_unit_max"
 		fi
 
 		test_desc="TEST 9 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes + 512 "
 		test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should not be succesful"
-		bytes_to_write=$(( "${md_sysfs_atomic_unit_max_bytes}" + 512 ))
+		bytes_to_write=$(( "${md_sysfs_atomic_unit_max}" + 512 ))
 		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
 		if [ "$bytes_written" = "" ]
 		then
@@ -221,15 +211,15 @@ _md_atomics_test() {
 
 		test_desc="TEST 10 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_min_bytes "
 		test_desc+="with RWF_ATOMIC flag - pwritev2 should be succesful"
-		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_min_bytes")
-		if [ "$bytes_written" = "$md_sysfs_atomic_unit_min_bytes" ]
+		bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$md_sysfs_atomic_unit_min")
+		if [ "$bytes_written" = "$md_sysfs_atomic_unit_min" ]
 		then
 			echo "$test_desc - pass"
 		else
-			echo "$test_desc - fail $bytes_written - $md_atomic_min_bytes"
+			echo "$test_desc - fail $bytes_written - $md_atomic_unit_min"
 		fi
 
-		bytes_to_write=$(( "${md_sysfs_atomic_unit_min_bytes}" - "${md_sysfs_logical_block_size}" ))
+		bytes_to_write=$(( "${md_sysfs_atomic_unit_min}" - "${md_sysfs_logical_block_size}" ))
 		test_desc="TEST 11 RAID $raid_level - perform a pwritev2 with a size of sysfs_atomic_unit_min_bytes - 512 "
 		test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should fail"
 		if [ "$bytes_to_write" = 0 ]
@@ -245,18 +235,27 @@ _md_atomics_test() {
 			fi
 		fi
 		mdadm --stop /dev/md/blktests_md  2> /dev/null 1>&2
+		mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
+		mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
+		mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
+		mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
 
 		if [ "$raid_level" = 0 ] || [ "$raid_level" = 10 ]
 		then
-			chunk_gran=$(( "$expected_atomic_unit_max_bytes" / 4))
-			if [ "$chunk_gran" -lt "$expected_atomic_unit_min_bytes" ]
+			chunk_gran=$(( "$expected_atomic_unit_max" / 4))
+			if [ "$chunk_gran" -lt "$expected_atomic_unit_min" ]
 			then
-				chunk_gran=$expected_atomic_unit_min_bytes
+				chunk_gran=$expected_atomic_unit_min
 			fi
 			local chunk_multiple=1
 			for step in `seq 1 6`
 			do
 				echo "chunky1 chunk_gran="$chunk_gran" raid_level="$raid_level" step="$step
+				local expected_chunk_atomic_unit_min
+				local expected_chunk_atomic_unit_max
+				local expected_chunk_atomic_max
+				local expected_chunk_atomic_boundary
+				
 
 				if [ "$raid_level" = 0 ]
 				then
@@ -264,40 +263,33 @@ _md_atomics_test() {
 				else
 					chunk_multiple=$(( 2 * "$chunk_multiple"))
 				fi
-				md_chunk_size_bytes=$(( "$chunk_gran" * "$chunk_multiple"))
-				echo "chunky2 md_chunk_size_bytes="$md_chunk_size_bytes" chunk_multiple="$chunk_multiple
-				md_chunk_size=$(( "$md_chunk_size_bytes" / 1024))
+				md_chunk_size=$(( "$chunk_gran" * "$chunk_multiple"))
+				echo "chunky2 md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple
+				md_chunk_size_kb=$(( "$md_chunk_size" / 1024))
 
-				if [ "$raid_level" = 0 ]
-				then
-					echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-						--raid-devices=2 --chunk="${md_chunk_size}"K --force \
-						/dev/"${dev0}" /dev/"${dev1}" 2> /dev/null 1>&2
-				else
-					echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
-						--raid-devices=4 --chunk="${md_chunk_size}"K --force \
+				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
+						--raid-devices=4 --chunk="${md_chunk_size_kb}"K --force \
 						/dev/"${dev0}" /dev/"${dev1}" \
 						/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
-				fi
-
+				
 				md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
 				md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"
-				md_sysfs_atomic_unit_max_bytes=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
+				md_sysfs_atomic_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
 				test_desc="TEST 12 RAID $raid_level - Verify chunk size "
-				echo "chunky3x md_chunk_size_bytes="$md_chunk_size_bytes" chunk_multiple="$chunk_multiple" md_sysfs_atomic_unit_max_bytes="$md_sysfs_atomic_unit_max_bytes
-				if [ "$md_chunk_size_bytes" -ge "$md_sysfs_atomic_unit_max_bytes" ] && \
-					(( md_chunk_size_bytes % md_sysfs_atomic_unit_max_bytes == 0 ))
+				echo "chunky3x md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple" md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max
+				if [ "$md_chunk_size" -ge "$md_sysfs_atomic_unit_max" ] && \
+					(( md_chunk_size % md_sysfs_atomic_unit_max == 0 ))
 				then
 					echo "$test_desc - pass"
 				else
-					echo $test_desc" - fail md_chunk_size_bytes="$md_chunk_size_bytes" md_sysfs_atomic_unit_max_bytes="$md_sysfs_atomic_unit_max_bytes" chunk_multiple="$chunk_multiple
+					echo $test_desc" - fail md_chunk_size="$md_chunk_size" md_sysfs_atomic_unit_max="$md_sysfs_atomic_unit_max" chunk_multiple="$chunk_multiple
 				fi
 
 				mdadm --quiet --stop /dev/md/blktests_md
-				mdadm --zero-superblock /dev/"${dev0}"
-				mdadm --zero-superblock /dev/"${dev1}"
-				mdadm --zero-superblock /dev/"${dev2}"
-				mdadm --zero-superblock /dev/"${dev3}"
+				mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
+				mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
+				mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
+				mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
 			done
 		fi
 	done
